# Generated by Django 3.0 on 2019-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.BigIntegerField()),
                ('video_name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('duration', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('video_path', models.CharField(max_length=300)),
            ],
        ),
    ]
